version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "automatic"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "niba97"
    assignees:
      - "niba97" 